package commands

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	mcpserver "github.com/luis-lozano/gitflow-helper/internal/mcp"
	"github.com/luis-lozano/gitflow-helper/internal/output"
	"github.com/spf13/cobra"
)

func newServeCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "serve",
		Short: "Start gitflow as an MCP server (stdio transport, for IDE integration)",
		Long: `Starts gitflow as a Model Context Protocol (MCP) server communicating
over stdin/stdout. IDEs like Cursor, Claude Code, and VS Code can connect
to this server to execute gitflow commands directly from the AI agent.

The server exposes all 14 gitflow tools: status, init, pull, sync, switch,
backmerge, cleanup, health, doctor, log, undo, releasenotes, start, finish.

Configuration is auto-generated by 'gitflow setup' into .cursor/mcp.json
or the equivalent IDE config file.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if output.IsJSONMode() {
				output.JSONOutput(map[string]any{
					"action":  "serve",
					"status":  "starting",
					"message": "MCP server starting on stdio transport",
				})
			}

			srv := mcpserver.NewServer(GF)

			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()

			sigCh := make(chan os.Signal, 1)
			signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
			go func() {
				<-sigCh
				cancel()
			}()

			return srv.Run(ctx)
		},
	}
}
